version: "3.8"
services:
    mongodb:
        image: 'mongo'
        ports:
          - '27017:27017'
        volumes: 
            - data:/data/db
        # environment:
        #     MONGO_INITDB_ROOT_USERNAME: max
        #     MONGO_INITDB_ROOT_PASSWORD: secret
    backend:
        build: ./
        ports:
            - '4000:4000'
        volumes:
            - ./src:/home/node/app/src
            - ./home/node/app
            - /home/node/app/node_modules
        env_file:
             - ./.env
        depends_on:
            - mongodb
volumes:
    data: