apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ankurdwivedi/padboat-backend:latest
          env:
            - name: AWS_ID
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: AWS_ID
            - name: AWS_SECRET
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: AWS_SECRET
            - name: BASE_URL
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: BASE_URL
            - name: AWS_REGION_NAME
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: AWS_REGION_NAME
            - name: AWS_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: AWS_BUCKET_NAME
            - name: ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: ACCESS_TOKEN_SECRET
            - name: REFRESH_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: REFRESH_TOKEN_SECRET
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: MONGO_URL
            - name: OTP_KEY
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: OTP_KEY
              # value: "mongodb://mongodb-service.default:27017/padboat"
              # value: "mongodb+srv://admin:1HKgUksK7q8QDJdM@cluster0.cibal.mongodb.net/padboat"